export interface UserProfile {
  id: number
  name: string
  username: string
  avatar: string
  followers: string
  verified: boolean
  specialty: string
  description: string
  bio: string
  location: string
  website: string
  joinDate: string
  following: number
  stories: number
  totalViews: string
}

export interface Post {
  id: number
  userId: number
  title: string
  description: string
  thumbnail: string
  author: string
  views: number
  likes: number
  comments: number
  shares: number
  timestamp: Date
  duration: string
  location?: string
  trending?: boolean
}

export const userProfiles: UserProfile[] = [
  {
    id: 1,
    name: "Sarah Chen",
    username: "@sarahchen_news",
    avatar: "/professional-asian-female-climate-journalist-with-.jpg",
    followers: "16.2k",
    verified: true,
    specialty: "Climate Reporter",
    description:
      "Award-winning environmental journalist covering climate change and sustainability issues across the globe.",
    bio: "Independent journalist covering climate change and environmental issues. Based in Iceland. 🌍",
    location: "Reykjavik, Iceland",
    website: "sarahchen.news",
    joinDate: "March 2023",
    following: 892,
    stories: 47,
    totalViews: "2.1M",
  },
  {
    id: 2,
    name: "Sarah Mitchell",
    username: "@sarahmitchell_photo",
    avatar: "/professional-female-photojournalist-with-camera-eq.jpg",
    followers: "12.8k",
    verified: true,
    specialty: "Photojournalist",
    description:
      "Award-winning photojournalist capturing powerful visual stories from conflict zones and humanitarian crises worldwide.",
    bio: "Photojournalist documenting stories that matter. Pulitzer Prize nominee. 📸",
    location: "New York, NY",
    website: "sarahmitchell.photo",
    joinDate: "January 2022",
    following: 654,
    stories: 38,
    totalViews: "1.8M",
  },
  {
    id: 3,
    name: "David Chen",
    username: "@davidchen_edit",
    avatar: "/professional-asian-male-video-editor-at-editing-st.jpg",
    followers: "9.4k",
    verified: true,
    specialty: "Video Editor",
    description:
      "Emmy-nominated video editor specializing in documentary storytelling and investigative journalism pieces.",
    bio: "Video editor crafting compelling narratives. Emmy nominee. Storyteller at heart. 🎬",
    location: "Los Angeles, CA",
    website: "davidchen.media",
    joinDate: "August 2021",
    following: 423,
    stories: 52,
    totalViews: "1.4M",
  },
  {
    id: 4,
    name: "Emily Rodriguez",
    username: "@emilyrodriguez_research",
    avatar: "/professional-latina-female-researcher-with-documen.jpg",
    followers: "8.7k",
    verified: true,
    specialty: "Research Journalist",
    description:
      "Investigative researcher and fact-checker ensuring accuracy and depth in complex investigative stories.",
    bio: "Research journalist & fact-checker. Truth matters. Data-driven storytelling. 🔍",
    location: "Washington, DC",
    website: "emilyrodriguez.news",
    joinDate: "May 2022",
    following: 512,
    stories: 29,
    totalViews: "1.1M",
  },
  {
    id: 5,
    name: "Marcus Thompson",
    username: "@mthompson_tech",
    avatar: "/professional-black-male-tech-journalist-in-silicon.jpg",
    followers: "23.5k",
    verified: true,
    specialty: "Tech Journalist",
    description:
      "Silicon Valley correspondent covering AI, cybersecurity, and emerging technologies shaping our future.",
    bio: "Tech journalist reporting on AI, startups, and innovation. Former engineer turned storyteller. 💻",
    location: "San Francisco, CA",
    website: "marcustech.io",
    joinDate: "January 2022",
    following: 1245,
    stories: 89,
    totalViews: "3.8M",
  },
  {
    id: 6,
    name: "Dr. Emily Watson",
    username: "@emilywatson_sci",
    avatar: "/professional-female-scientist-in-lab-coat-with-mic.jpg",
    followers: "45.3k",
    verified: true,
    specialty: "Science Writer",
    description:
      "PhD in molecular biology turned science communicator, making complex research accessible to everyone.",
    bio: "Science writer & researcher. Making complex discoveries understandable. PhD in Molecular Biology. 🔬",
    location: "Boston, MA",
    website: "emilywatson.science",
    joinDate: "June 2021",
    following: 678,
    stories: 124,
    totalViews: "5.2M",
  },
  {
    id: 7,
    name: "Rep. Maria Rodriguez",
    username: "@reprodriguez",
    avatar: "/professional-latina-congresswoman-in-formal-attire.jpg",
    followers: "89.7k",
    verified: true,
    specialty: "Congresswoman",
    description:
      "U.S. Representative fighting for healthcare reform, education, and economic justice for all Americans.",
    bio: "Congresswoman representing District 12. Fighting for healthcare, education, and justice. 🇺🇸",
    location: "Washington, DC",
    website: "rodriguez.house.gov",
    joinDate: "November 2020",
    following: 234,
    stories: 156,
    totalViews: "8.9M",
  },
  {
    id: 8,
    name: "David Park",
    username: "@davidpark_zoo",
    avatar: "/professional-asian-male-zookeeper-with-animals-in-.jpg",
    followers: "34.6k",
    verified: true,
    specialty: "Wildlife Expert",
    description:
      "Head zookeeper and wildlife conservationist sharing stories of animal behavior and conservation efforts.",
    bio: "Zookeeper & wildlife conservationist. Protecting endangered species one story at a time. 🦁",
    location: "San Diego, CA",
    website: "wildlifewithpark.com",
    joinDate: "April 2022",
    following: 567,
    stories: 98,
    totalViews: "2.7M",
  },
  {
    id: 9,
    name: "Jessica Martinez",
    username: "@jmartinez_sports",
    avatar: "/professional-latina-female-sports-journalist-at-st.jpg",
    followers: "67.8k",
    verified: true,
    specialty: "Sports Reporter",
    description:
      "ESPN correspondent covering NBA, NFL, and Olympic sports with exclusive player interviews and analysis.",
    bio: "Sports journalist covering the biggest games and athletes. ESPN correspondent. 🏀⚽",
    location: "New York, NY",
    website: "jessicasports.com",
    joinDate: "September 2021",
    following: 1890,
    stories: 234,
    totalViews: "6.4M",
  },
  {
    id: 10,
    name: "Chef Antoine Dubois",
    username: "@chefantoine",
    avatar: "/professional-french-male-chef-in-kitchen-with-mich.jpg",
    followers: "52.3k",
    verified: true,
    specialty: "Food Critic",
    description:
      "Michelin-starred chef and food critic exploring culinary traditions and innovative cuisine worldwide.",
    bio: "Michelin-starred chef & food critic. Exploring flavors from around the world. 🍽️",
    location: "Paris, France",
    website: "antoinedubois.com",
    joinDate: "February 2023",
    following: 445,
    stories: 76,
    totalViews: "1.9M",
  },
  {
    id: 11,
    name: "Aisha Patel",
    username: "@aishapatel_travel",
    avatar: "/professional-indian-female-travel-journalist-with-.jpg",
    followers: "78.9k",
    verified: true,
    specialty: "Travel Journalist",
    description:
      "Adventure journalist documenting hidden gems, cultural experiences, and sustainable travel across 6 continents.",
    bio: "Travel journalist & photographer. 127 countries and counting. Sustainable travel advocate. ✈️",
    location: "Mumbai, India",
    website: "aishatravels.com",
    joinDate: "May 2020",
    following: 2134,
    stories: 189,
    totalViews: "7.8M",
  },
  {
    id: 12,
    name: "Robert Chen",
    username: "@robertchen_biz",
    avatar: "/professional-asian-male-business-analyst-on-wall-s.jpg",
    followers: "41.2k",
    verified: true,
    specialty: "Business Analyst",
    description: "Wall Street analyst covering markets, startups, and economic trends with data-driven insights.",
    bio: "Business analyst & market strategist. Breaking down complex economics for everyone. 📊",
    location: "New York, NY",
    website: "chenbusiness.com",
    joinDate: "August 2022",
    following: 789,
    stories: 112,
    totalViews: "3.2M",
  },
  {
    id: 13,
    name: "Zoe Williams",
    username: "@zoewilliams_ent",
    avatar: "/professional-female-entertainment-journalist-at-re.jpg",
    followers: "94.5k",
    verified: true,
    specialty: "Entertainment Reporter",
    description: "Hollywood insider covering film, music, and celebrity news with exclusive red carpet interviews.",
    bio: "Entertainment journalist covering Hollywood's biggest stories. Red carpet regular. 🎬",
    location: "Los Angeles, CA",
    website: "zoewilliams.tv",
    joinDate: "March 2021",
    following: 3456,
    stories: 267,
    totalViews: "9.8M",
  },
  {
    id: 14,
    name: "Dr. James Morrison",
    username: "@drmorrison_health",
    avatar: "/male-doctor-stethoscope.png",
    followers: "56.7k",
    verified: true,
    specialty: "Health Expert",
    description: "Medical doctor and health journalist translating medical research into practical wellness advice.",
    bio: "MD & health journalist. Evidence-based wellness and medical news you can trust. 🏥",
    location: "Seattle, WA",
    website: "drmorrison.health",
    joinDate: "July 2022",
    following: 456,
    stories: 134,
    totalViews: "4.1M",
  },
  {
    id: 15,
    name: "Prof. Linda Chang",
    username: "@profchang_edu",
    avatar: "/professional-asian-female-professor-in-classroom-t.jpg",
    followers: "38.9k",
    verified: true,
    specialty: "Education Specialist",
    description:
      "Education professor and policy expert advocating for equitable access to quality education worldwide.",
    bio: "Education professor & policy advocate. Fighting for every child's right to learn. 📚",
    location: "Chicago, IL",
    website: "lindachang.edu",
    joinDate: "October 2021",
    following: 567,
    stories: 87,
    totalViews: "2.3M",
  },
  {
    id: 16,
    name: "Detective Mike Sullivan",
    username: "@detectivesullivan",
    avatar: "/professional-male-detective-investigative-journali.jpg",
    followers: "72.4k",
    verified: true,
    specialty: "Crime Reporter",
    description:
      "Former detective turned investigative journalist uncovering truth in criminal justice and cold cases.",
    bio: "Investigative journalist & former detective. Seeking justice through storytelling. 🔍",
    location: "Chicago, IL",
    website: "sullivaninvestigates.com",
    joinDate: "December 2020",
    following: 890,
    stories: 156,
    totalViews: "6.7M",
  },
  {
    id: 17,
    name: "Isabella Rossi",
    username: "@isabellarossi_fashion",
    avatar: "/professional-italian-female-fashion-journalist-at-.jpg",
    followers: "103.2k",
    verified: true,
    specialty: "Fashion Journalist",
    description: "Vogue contributor covering haute couture, street style, and sustainable fashion from Milan to Tokyo.",
    bio: "Fashion journalist covering runways worldwide. Vogue contributor. Sustainable fashion advocate. 👗",
    location: "Milan, Italy",
    website: "isabellarossi.style",
    joinDate: "January 2021",
    following: 4567,
    stories: 298,
    totalViews: "11.2M",
  },
  {
    id: 18,
    name: "Jake Morrison",
    username: "@jakemorrison_auto",
    avatar: "/professional-male-automotive-journalist-with-sport.jpg",
    followers: "48.3k",
    verified: true,
    specialty: "Automotive Expert",
    description:
      "Car enthusiast and automotive journalist reviewing the latest vehicles and covering industry innovations.",
    bio: "Automotive journalist & car enthusiast. Test driving the future of transportation. 🚗",
    location: "Detroit, MI",
    website: "jakemorrison.auto",
    joinDate: "June 2022",
    following: 678,
    stories: 145,
    totalViews: "3.6M",
  },
  {
    id: 19,
    name: "Rachel Goldman",
    username: "@rachelgoldman_realestate",
    avatar: "/professional-female-real-estate-analyst-with-city-.jpg",
    followers: "61.5k",
    verified: true,
    specialty: "Real Estate Analyst",
    description:
      "Real estate expert analyzing market trends, investment opportunities, and urban development nationwide.",
    bio: "Real estate analyst covering housing markets and urban development. Making property accessible. 🏠",
    location: "Miami, FL",
    website: "goldmanrealestate.com",
    joinDate: "April 2021",
    following: 1234,
    stories: 167,
    totalViews: "4.8M",
  },
  {
    id: 20,
    name: "Dr. Neil Armstrong Jr.",
    username: "@neilarmstrong_space",
    avatar: "/professional-male-astrophysicist-space-journalist-.jpg",
    followers: "87.6k",
    verified: true,
    specialty: "Space Reporter",
    description:
      "Astrophysicist and space journalist covering NASA missions, private space exploration, and cosmic discoveries.",
    bio: "Astrophysicist & space journalist. Bringing the universe closer to Earth. 🚀",
    location: "Houston, TX",
    website: "neilarmstrong.space",
    joinDate: "February 2022",
    following: 567,
    stories: 178,
    totalViews: "7.9M",
  },
  {
    id: 21,
    name: "Maya Johnson",
    username: "@mayajohnson_culture",
    avatar: "/professional-black-female-cultural-critic-at-art-g.jpg",
    followers: "54.8k",
    verified: true,
    specialty: "Cultural Critic",
    description: "Cultural critic examining art, literature, and social movements shaping contemporary society.",
    bio: "Cultural critic & arts journalist. Exploring how culture shapes our world. 🎨",
    location: "London, UK",
    website: "mayajohnson.culture",
    joinDate: "September 2021",
    following: 890,
    stories: 134,
    totalViews: "4.2M",
  },
  {
    id: 22,
    name: "Prof. David Lee",
    username: "@proflee_economics",
    avatar: "/professional-asian-male-economics-professor-with-c.jpg",
    followers: "43.7k",
    verified: true,
    specialty: "Economic Analyst",
    description: "Economics professor analyzing global markets, trade policies, and their impact on everyday people.",
    bio: "Economics professor making sense of markets and policies. Nobel Prize nominee. 💰",
    location: "Cambridge, MA",
    website: "davidlee.economics",
    joinDate: "November 2021",
    following: 345,
    stories: 98,
    totalViews: "3.1M",
  },
  {
    id: 23,
    name: "Alex Rivera",
    username: "@alexrivera_news",
    avatar: "/professional-latino-male-investigative-journalist-.jpg",
    followers: "18.3k",
    verified: true,
    specialty: "Investigative Reporter",
    description:
      "Investigative journalist uncovering corruption and holding power accountable through in-depth reporting.",
    bio: "Investigative reporter exposing truth. Award-winning journalist. Justice through journalism. 🔎",
    location: "Miami, FL",
    website: "alexrivera.news",
    joinDate: "April 2022",
    following: 723,
    stories: 64,
    totalViews: "2.4M",
  },
  {
    id: 24,
    name: "Maria Santos",
    username: "@mariasantos_global",
    avatar: "/professional-latina-female-international-correspon.jpg",
    followers: "21.7k",
    verified: true,
    specialty: "International Correspondent",
    description:
      "Foreign correspondent reporting on global conflicts, humanitarian crises, and international diplomacy.",
    bio: "International correspondent covering stories that shape our world. Based in Brussels. 🌍",
    location: "Brussels, Belgium",
    website: "mariasantos.global",
    joinDate: "June 2021",
    following: 891,
    stories: 82,
    totalViews: "3.1M",
  },
  {
    id: 25,
    name: "Dr. James Wilson",
    username: "@drwilson_policy",
    avatar: "/professional-male-policy-analyst-at-capitol-buildi.jpg",
    followers: "32.4k",
    verified: true,
    specialty: "Policy Analyst",
    description: "Political scientist and policy expert analyzing government decisions and their impact on society.",
    bio: "PhD in Political Science. Policy analyst making sense of government decisions. 📜",
    location: "Washington, DC",
    website: "jameswilson.policy",
    joinDate: "September 2020",
    following: 567,
    stories: 94,
    totalViews: "3.8M",
  },
  {
    id: 26,
    name: "Lisa Chen",
    username: "@lisachen_digital",
    avatar: "/professional-asian-female-digital-media-strategist.jpg",
    followers: "15.9k",
    verified: true,
    specialty: "Digital Media Strategist",
    description:
      "Digital media expert covering social media trends, online culture, and the future of digital journalism.",
    bio: "Digital media strategist & journalist. Exploring how technology shapes storytelling. 💻",
    location: "San Francisco, CA",
    website: "lisachen.digital",
    joinDate: "March 2022",
    following: 634,
    stories: 57,
    totalViews: "1.9M",
  },
  {
    id: 27,
    name: "Marcus Johnson",
    username: "@marcusjohnson_urban",
    avatar: "/professional-black-male-urban-affairs-journalist-i.jpg",
    followers: "19.6k",
    verified: true,
    specialty: "Urban Affairs Reporter",
    description:
      "Urban affairs journalist covering housing, transportation, and community development in major cities.",
    bio: "Urban affairs reporter telling stories of cities and communities. Building better neighborhoods. 🏙️",
    location: "Chicago, IL",
    website: "marcusjohnson.urban",
    joinDate: "January 2023",
    following: 445,
    stories: 48,
    totalViews: "1.7M",
  },
  {
    id: 28,
    name: "Sarah Kim",
    username: "@sarahkim_culture",
    avatar: "/professional-korean-female-culture-journalist-at-a.jpg",
    followers: "24.8k",
    verified: true,
    specialty: "Culture Reporter",
    description:
      "Cultural journalist exploring art, music, literature, and the stories that define our shared humanity.",
    bio: "Culture reporter celebrating creativity and human expression. Arts advocate. 🎨",
    location: "Seoul, South Korea",
    website: "sarahkim.culture",
    joinDate: "July 2021",
    following: 1023,
    stories: 76,
    totalViews: "2.8M",
  },
  {
    id: 29,
    name: "Emma Rodriguez",
    username: "@emmarodriguez_human",
    avatar: "/professional-latina-female-human-rights-journalist.jpg",
    followers: "27.3k",
    verified: true,
    specialty: "Human Rights Reporter",
    description: "Human rights journalist documenting injustice and amplifying voices of the marginalized worldwide.",
    bio: "Human rights reporter fighting for justice through storytelling. Every voice matters. ✊",
    location: "Geneva, Switzerland",
    website: "emmarodriguez.rights",
    joinDate: "February 2021",
    following: 812,
    stories: 91,
    totalViews: "3.4M",
  },
  {
    id: 30,
    name: "Fatima Hassan",
    username: "@fatimahassan_rights",
    avatar: "/professional-middle-eastern-female-human-rights-la.jpg",
    followers: "76.9k",
    verified: true,
    specialty: "Human Rights Activist",
    description:
      "Human rights lawyer and journalist documenting social justice movements and advocating for marginalized communities.",
    bio: "Human rights lawyer & journalist. Fighting for justice and equality worldwide. ✊",
    location: "Geneva, Switzerland",
    website: "fatimahassan.org",
    joinDate: "May 2020",
    following: 1567,
    stories: 189,
    totalViews: "8.3M",
  },
]

export const allPosts: Post[] = [
  // Sarah Chen (Climate Reporter - Iceland) - Posts 1-10
  {
    id: 1,
    userId: 1,
    title: "Local Geothermal Plant Powers 200 More Homes",
    description:
      "Reykjavik's newest geothermal facility came online this week, providing clean energy to the growing neighborhood.",
    thumbnail: "/geothermal-power-plant-with-steam-rising-in-icelan.jpg",
    author: "Sarah Chen",
    views: 12400,
    likes: 890,
    comments: 67,
    shares: 145,
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    duration: "1:45",
    location: "Reykjavik, Iceland",
  },
  {
    id: 2,
    userId: 1,
    title: "Neighbors Start Community Composting Program",
    description:
      "Three families on my street just set up a shared compost bin. Small steps toward reducing waste in our neighborhood.",
    thumbnail: "/community-compost-bin-in-residential-neighborhood.jpg",
    author: "Sarah Chen",
    views: 8900,
    likes: 654,
    comments: 43,
    shares: 89,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    duration: "1:12",
    location: "Reykjavik, Iceland",
  },
  {
    id: 3,
    userId: 1,
    title: "Checking In on the Glacier I Visit Every Month",
    description:
      "Been documenting this glacier for 2 years now. You can really see the changes when you visit regularly.",
    thumbnail: "/volcanic-sunset.png",
    author: "Sarah Chen",
    views: 15600,
    likes: 1240,
    comments: 89,
    shares: 234,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    duration: "2:03",
    location: "Ilulissat, Greenland",
  },
  {
    id: 4,
    userId: 1,
    title: "This Cafe Switched to Reusable Cups Only",
    description:
      "My favorite coffee shop just went completely reusable. They're washing cups on-site instead of using disposables.",
    thumbnail: "/cozy-cafe-interior-with-reusable-coffee-cups.jpg",
    author: "Sarah Chen",
    views: 11200,
    likes: 823,
    comments: 56,
    shares: 167,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    duration: "1:34",
    location: "Reykjavik, Iceland",
  },
  {
    id: 5,
    userId: 1,
    title: "Interview with My 87-Year-Old Neighbor About Climate",
    description:
      "She's lived here her whole life and has incredible stories about how the weather has changed over the decades.",
    thumbnail: "/interview-with-elderly-person-in-their-home.jpg",
    author: "Sarah Chen",
    views: 19800,
    likes: 1567,
    comments: 134,
    shares: 345,
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    duration: "3:12",
    location: "Oslo, Norway",
  },
  {
    id: 6,
    userId: 1,
    title: "Local School Adds Solar Panels to Roof",
    description:
      "The elementary school down the street just installed solar panels. Kids are learning about renewable energy firsthand.",
    thumbnail: "/modern-building-news.png",
    author: "Sarah Chen",
    views: 13400,
    likes: 967,
    comments: 78,
    shares: 198,
    timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    duration: "1:56",
    location: "Reykjavik, Iceland",
  },
  {
    id: 7,
    userId: 1,
    title: "My Apartment Building Just Got Solar Panels",
    description:
      "Our landlord installed solar panels on the roof. It's going to reduce our electricity costs and carbon footprint.",
    thumbnail: "/solar-panels-on-apartment-building-roof.jpg",
    author: "Sarah Chen",
    views: 10500,
    likes: 734,
    comments: 52,
    shares: 134,
    timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    duration: "1:28",
    location: "Copenhagen, Denmark",
  },
  {
    id: 8,
    userId: 1,
    title: "Grocery Store Checkout: Reusable Bags Only",
    description: "The local grocery store stopped offering plastic bags entirely. Everyone brings their own bags now.",
    thumbnail: "/grocery-store-checkout-with-reusable-bags.jpg",
    author: "Sarah Chen",
    views: 9800,
    likes: 689,
    comments: 45,
    shares: 112,
    timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    duration: "1:15",
    location: "Reykjavik, Iceland",
  },
  {
    id: 9,
    userId: 1,
    title: "Wind Turbines on the Hill Behind My House",
    description:
      "These turbines have been here for years, but I never get tired of watching them spin. Clean energy in action.",
    thumbnail: "/wind-turbines-on-hillside-in-iceland.jpg",
    author: "Sarah Chen",
    views: 14200,
    likes: 1034,
    comments: 67,
    shares: 189,
    timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000),
    duration: "1:42",
    location: "Reykjavik, Iceland",
  },
  {
    id: 10,
    userId: 1,
    title: "Tour of the Local Recycling Facility",
    description: "Got a behind-the-scenes look at where our recycling actually goes. It's more complex than I thought!",
    thumbnail: "/recycling-sorting-facility-with-workers.jpg",
    author: "Sarah Chen",
    views: 11900,
    likes: 856,
    comments: 61,
    shares: 156,
    timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000),
    duration: "2:34",
    location: "Reykjavik, Iceland",
  },

  // Sarah Mitchell (NYC Photojournalist) - Now 8 posts in US (NYC), 2 in UK
  {
    id: 11,
    userId: 2,
    title: "Morning Rush at Grand Central",
    description: "Caught this moment during the 8am commuter wave. The light coming through the windows was perfect.",
    thumbnail: "/morning-rush-hour-at-grand-central-terminal-with-c.jpg",
    author: "Sarah Mitchell",
    views: 18900,
    likes: 1560,
    comments: 87,
    shares: 234,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    duration: "0:45",
    location: "Manhattan, NY",
    trending: true,
  },
  {
    id: 12,
    userId: 2,
    title: "Street Vendor's 30 Years on the Same Corner",
    description:
      "Mohammed has been selling hot dogs on 53rd and 6th for three decades. His story is NYC in a nutshell.",
    thumbnail: "/street-vendor-selling-hot-dogs-in-new-york-city.jpg",
    author: "Sarah Mitchell",
    views: 22400,
    likes: 1890,
    comments: 124,
    shares: 456,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    duration: "2:12",
    location: "Manhattan, NY",
  },
  {
    id: 13,
    userId: 2,
    title: "Subway Musician's Daily Performance",
    description: "This saxophonist plays the same spot every Tuesday. Today a kid started dancing and everyone smiled.",
    thumbnail: "/saxophonist-performing-in-subway-station.jpg",
    author: "Sarah Mitchell",
    views: 16700,
    likes: 1340,
    comments: 76,
    shares: 289,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    duration: "1:34",
    location: "Union Square Station, NY",
  },
  {
    id: 14,
    userId: 2,
    title: "Bodega Cat Has Become Neighborhood Celebrity",
    description: "Customers come to this bodega just to see Whiskers. He's been here for 7 years and knows everyone.",
    thumbnail: "/cat-sitting-in-bodega-store.jpg",
    author: "Sarah Mitchell",
    views: 31200,
    likes: 2890,
    comments: 167,
    shares: 678,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    duration: "1:23",
    location: "Brooklyn, NY",
  },
  {
    id: 15,
    userId: 2,
    title: "Neighbors Argue Over Parking Spot (Again)",
    description: "Same two guys, same parking dispute, every week. This is the most NYC thing I could imagine.",
    thumbnail: "/neighbors-arguing-over-parking-spot.jpg",
    author: "Sarah Mitchell",
    views: 19800,
    likes: 1560,
    comments: 87,
    shares: 234,
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    duration: "1:45",
    location: "Manhattan, NY",
  },
  {
    id: 16,
    userId: 2,
    title: "Hot Dog Stand in Times Square at Night",
    description: "The iconic Times Square hot dog stand. A classic NYC experience.",
    thumbnail: "/hot-dog-stand-in-times-square-at-night.jpg",
    author: "Sarah Mitchell",
    views: 25600,
    likes: 2120,
    comments: 108,
    shares: 456,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    duration: "1:15",
    location: "Times Square, NY",
  },
  {
    id: 17,
    userId: 2,
    title: "Central Park Runner at Sunrise",
    description: "Early morning runners in Central Park. The city is just waking up.",
    thumbnail: "/runner-in-central-park-at-sunrise.jpg",
    author: "Sarah Mitchell",
    views: 17800,
    likes: 1450,
    comments: 89,
    shares: 312,
    timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    duration: "0:58",
    location: "Central Park, NY",
  },
  {
    id: 18,
    userId: 2,
    title: "View of the Manhattan Skyline from Brooklyn Bridge",
    description: "The best view of Manhattan is from the Brooklyn Bridge at dusk.",
    thumbnail: "/manhattan-skyline-view-from-brooklyn-bridge-at-dus.jpg",
    author: "Sarah Mitchell",
    views: 30200,
    likes: 2670,
    comments: 156,
    shares: 789,
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    duration: "1:34",
    location: "London, UK", // Moved to UK
    trending: true,
  },
  {
    id: 19,
    userId: 2,
    title: "Street Art in Bushwick Graffiti",
    description: "Bushwick is an outdoor art gallery. So much talent on these walls.",
    thumbnail: "/street-art-graffiti-in-bushwick-neighborhood.jpg",
    author: "Sarah Mitchell",
    views: 19400,
    likes: 1520,
    comments: 108,
    shares: 412,
    timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    duration: "2:12",
    location: "London, UK", // Moved to UK
  },
  {
    id: 20,
    userId: 2,
    title: "Yellow Cab Driving Through City Streets",
    description: "The quintessential NYC yellow cab. Always a classic sight.",
    thumbnail: "/yellow-taxi-cab-driving-through-new-york-city-str.jpg",
    author: "Sarah Mitchell",
    views: 15800,
    likes: 1180,
    comments: 76,
    shares: 289,
    timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    duration: "0:45",
    location: "Manhattan, NY",
  },

  // David Chen (LA Video Editor) - Now 5 posts in US (LA), 3 in Japan, 2 in India
  {
    id: 21,
    userId: 3,
    title: "Editing a Documentary About Local Skate Culture",
    description:
      "Spent 6 months filming skaters in Venice Beach. The editing process is where the real story comes together.",
    thumbnail: "/video-editing-timeline-with-skateboarding-footage.jpg",
    author: "David Chen",
    views: 24500,
    likes: 1890,
    comments: 245,
    shares: 456,
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    duration: "2:34",
    location: "Tokyo, Japan", // Moved to Japan
  },
  {
    id: 22,
    userId: 3,
    title: "Why I Switched from Premiere to DaVinci Resolve",
    description:
      "After 10 years on Premiere, I made the switch. Here's what I learned about color grading and workflow.",
    thumbnail: "/video-editing-software-comparison-screens.jpg",
    author: "David Chen",
    views: 18700,
    likes: 1340,
    comments: 156,
    shares: 389,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    duration: "3:45",
    location: "Tokyo, Japan", // Moved to Japan
  },
  {
    id: 23,
    userId: 3,
    title: "Behind the Scenes: Editing a Wedding Video",
    description:
      "Clients want their wedding to look cinematic. Here's how I turn 8 hours of footage into a 10-minute story.",
    thumbnail: "/wedding-video-editing-timeline.jpg",
    author: "David Chen",
    views: 15200,
    likes: 1120,
    comments: 98,
    shares: 267,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    duration: "2:12",
    location: "Tokyo, Japan", // Moved to Japan
  },
  {
    id: 24,
    userId: 3,
    title: "Sound Design Tips for Documentary Filmmakers",
    description:
      "Good audio is 50% of the story. Here are my favorite techniques for mixing dialogue and ambient sound.",
    thumbnail: "/audio-waveforms-and-sound-mixing-interface.jpg",
    author: "David Chen",
    views: 12800,
    likes: 945,
    comments: 87,
    shares: 234,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    duration: "2:56",
    location: "Los Angeles, CA",
  },
  {
    id: 25,
    userId: 3,
    title: "My Editing Setup: Hardware and Software Tour",
    description: "People always ask about my setup. Here's everything I use for professional video editing.",
    thumbnail: "/professional-video-editing-workstation-setup.jpg",
    author: "David Chen",
    views: 21400,
    likes: 1670,
    comments: 134,
    shares: 445,
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    duration: "3:23",
    location: "Los Angeles, CA",
  },
  {
    id: 26,
    userId: 3,
    title: "Color Grading Before and After Comparison",
    description: "Same footage, completely different mood. Color grading is where the magic happens.",
    thumbnail: "/before-and-after-color-grading-comparison.jpg",
    author: "David Chen",
    views: 19600,
    likes: 1520,
    comments: 112,
    shares: 378,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    duration: "1:45",
    location: "Bangalore, India", // Moved to India
  },
  {
    id: 27,
    userId: 3,
    title: "Frustrated Video Editor at Computer with Error Screen",
    description: "When your project crashes right before the deadline. Every editor knows this pain.",
    thumbnail: "/frustrated-video-editor-at-computer-with-error-scr.jpg",
    author: "David Chen",
    views: 16800,
    likes: 1290,
    comments: 145,
    shares: 312,
    timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    duration: "0:58",
    location: "Bangalore, India", // Moved to India
  },
  {
    id: 28,
    userId: 3,
    title: "Video Editing Software Comparison on Multiple Monitors",
    description: "Testing Final Cut, Premiere, and DaVinci side by side. Which one is really the best?",
    thumbnail: "/video-editing-software-comparison-on-multiple-moni.jpg",
    author: "David Chen",
    views: 23100,
    likes: 1780,
    comments: 189,
    shares: 467,
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    duration: "4:12",
    location: "Los Angeles, CA",
  },
  {
    id: 29,
    userId: 3,
    title: "Wedding Ceremony Footage on Video Editing Timeline",
    description: "Breaking down how I structure a wedding edit. The ceremony is always the emotional core.",
    thumbnail: "/wedding-ceremony-footage-on-video-editing-timeline.jpg",
    author: "David Chen",
    views: 14500,
    likes: 1050,
    comments: 92,
    shares: 245,
    timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    duration: "2:34",
    location: "Los Angeles, CA",
  },
  {
    id: 30,
    userId: 3,
    title: "Audio Waveforms and Sound Mixing Interface",
    description: "Deep dive into audio mixing for video. This is where amateur editors become professionals.",
    thumbnail: "/audio-waveforms-and-sound-mixing-interface.jpg",
    author: "David Chen",
    views: 17200,
    likes: 1320,
    comments: 108,
    shares: 289,
    timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    duration: "3:45",
    location: "Los Angeles, CA",
  },

  // Emily Rodriguez (DC Research Journalist) - Keeping all 10 in Washington DC (high US engagement cluster)
  {
    id: 31,
    userId: 4,
    title: "Fact-Checking Local Council Meeting Claims",
    description: "The city council made some bold claims about the budget. I spent a week verifying every number.",
    thumbnail: "/city-council-meeting-with-people-at-podium.jpg",
    author: "Emily Rodriguez",
    views: 19800,
    likes: 1450,
    comments: 167,
    shares: 823,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    duration: "2:45",
    location: "Washington, DC, United States", // Changed from "USA" to "United States"
  },
  {
    id: 32,
    userId: 4,
    title: "Investigating City Hall Document Requests",
    description: "Filed 15 FOIA requests to get these documents. Transparency shouldn't be this hard.",
    thumbnail: "/person-reviewing-documents-and-files-at-city-hall.jpg",
    author: "Emily Rodriguez",
    views: 16400,
    likes: 1230,
    comments: 134,
    shares: 456,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    duration: "3:12",
    location: "Washington, DC, United States", // Changed from "USA" to "United States"
  },
  {
    id: 33,
    userId: 4,
    title: "Budget Analyst Explaining Financial Charts and Graphs",
    description: "Breaking down the city budget so everyone can understand where their tax dollars actually go.",
    thumbnail: "/budget-analyst-explaining-financial-charts-and-gra.jpg",
    author: "Emily Rodriguez",
    views: 14200,
    likes: 1050,
    comments: 98,
    shares: 378,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    duration: "2:34",
    location: "Washington, DC, United States", // Changed from "USA" to "United States"
  },
  {
    id: 34,
    userId: 4,
    title: "School Building with Budget Documents and Calculator",
    description: "The school district says they need more funding. Here's what the numbers actually show.",
    thumbnail: "/school-building-with-budget-documents-and-calculat.jpg",
    author: "Emily Rodriguez",
    views: 18600,
    likes: 1390,
    comments: 145,
    shares: 512,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    duration: "2:56",
    location: "Washington, DC, United States", // Changed from "USA" to "United States"
  },
  {
    id: 35,
    userId: 4,
    title: "Construction Site with Financial Documents Overlay",
    description: "Following the money on this public works project. The contracts tell an interesting story.",
    thumbnail: "/construction-site-with-financial-documents-overlay.jpg",
    author: "Emily Rodriguez",
    views: 15800,
    likes: 1180,
    comments: 112,
    shares: 445,
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    duration: "3:23",
    location: "Washington, DC, United States", // Changed from "USA" to "United States"
  },
  {
    id: 36,
    userId: 4,
    title: "Data Visualization of City Spending Patterns",
    description: "Created this visualization to show where the city spends the most money. Some surprises here.",
    thumbnail: "/data-visualization-charts-showing-city-budget-spen.jpg",
    author: "Emily Rodriguez",
    views: 21200,
    likes: 1620,
    comments: 156,
    shares: 589,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    duration: "1:45",
    location: "Washington, DC, United States", // Changed from "USA" to "United States"
  },
  {
    id: 37,
    userId: 4,
    title: "Interview with City Budget Director",
    description: "Asked the tough questions about budget priorities. The answers were... revealing.",
    thumbnail: "/professional-interview-in-government-office.jpg",
    author: "Emily Rodriguez",
    views: 17400,
    likes: 1310,
    comments: 128,
    shares: 467,
    timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    duration: "4:12",
    location: "Washington, DC, United States", // Changed from "USA" to "United States"
  },
  {
    id: 38,
    userId: 4,
    title: "Comparing Campaign Promises to Actual Votes",
    description: "What politicians say vs. how they vote. The data doesn't lie.",
    thumbnail: "/political-campaign-promises-vs-voting-record-compa.jpg",
    author: "Emily Rodriguez",
    views: 24800,
    likes: 1920,
    comments: 198,
    shares: 712,
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    duration: "3:34",
    location: "Washington, DC, United States", // Changed from "USA" to "United States"
  },
  {
    id: 39,
    userId: 4,
    title: "Public Records Request Tutorial",
    description: "How to file FOIA requests and get the documents you need. Transparency is a right.",
    thumbnail: "/person-filling-out-foia-request-form.jpg",
    author: "Emily Rodriguez",
    views: 13600,
    likes: 980,
    comments: 87,
    shares: 334,
    timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    duration: "2:23",
    location: "Washington, DC, United States", // Changed from "USA" to "United States"
  },
  {
    id: 40,
    userId: 4,
    title: "Analyzing Lobbyist Spending Reports",
    description: "Who's spending money to influence local policy? The numbers are eye-opening.",
    thumbnail: "/financial-reports-and-lobbying-documents.jpg",
    author: "Emily Rodriguez",
    views: 19200,
    likes: 1470,
    comments: 142,
    shares: 623,
    timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    duration: "3:12",
    location: "Washington, DC, United States", // Changed from "USA" to "United States"
  },

  // Marcus Thompson (SF Tech Journalist) - Now 4 in US (SF), 3 in Japan, 2 in India, 1 in Austin
  {
    id: 41,
    userId: 5,
    title: "Inside the Latest AI Startup Demo Day",
    description:
      "20 startups pitched their AI products today. Some are genuinely impressive, others are just buzzwords.",
    thumbnail: "/startup-pitch-presentation-with-ai-technology.jpg",
    author: "Marcus Thompson",
    views: 28400,
    likes: 3200,
    comments: 189,
    shares: 567,
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    duration: "3:45",
    location: "San Francisco, CA",
  },
  {
    id: 42,
    userId: 5,
    title: "Coffee Shop Full of People Working on Laptops",
    description: "Every coffee shop in SF looks like this. The startup culture is real.",
    thumbnail: "/coffee-shop-full-of-people-working-on-laptops.jpg",
    author: "Marcus Thompson",
    views: 16800,
    likes: 1290,
    comments: 98,
    shares: 312,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    duration: "1:23",
    location: "San Francisco, CA",
  },
  {
    id: 43,
    userId: 5,
    title: "Tech Worker Being Interviewed About Leaving San Francisco",
    description: "The exodus is real. Talked to 5 engineers who are moving to Austin this month.",
    thumbnail: "/tech-worker-being-interviewed-about-leaving-san-fr.jpg",
    author: "Marcus Thompson",
    views: 22100,
    likes: 1780,
    comments: 167,
    shares: 489,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    duration: "2:45",
    location: "Austin, TX", // Kept in Austin
  },
  {
    id: 44,
    userId: 5,
    title: "Coding Bootcamp Graduation Ceremony with Students",
    description: "These bootcamp grads are entering a tough job market. But their determination is inspiring.",
    thumbnail: "/coding-bootcamp-graduation-ceremony-with-students-.jpg",
    author: "Marcus Thompson",
    views: 14500,
    likes: 1050,
    comments: 87,
    shares: 267,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    duration: "2:12",
    location: "Tokyo, Japan", // Moved to Japan
  },
  {
    id: 45,
    userId: 5,
    title: "AI Startup Office with Machine Learning Technology",
    description: "Got exclusive access to this AI lab. What they're building could change everything.",
    thumbnail: "/ai-startup-office-with-machine-learning-technology.jpg",
    author: "Marcus Thompson",
    views: 31200,
    likes: 2450,
    comments: 212,
    shares: 678,
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    duration: "3:56",
    location: "Bangalore, India", // Moved to India
  },
  {
    id: 46,
    userId: 5,
    title: "Tech Meetup Networking Event at Bar with Developers",
    description: "The networking scene is alive and well. Everyone's looking for their next opportunity.",
    thumbnail: "/tech-meetup-networking-event-at-bar-with-developer.jpg",
    author: "Marcus Thompson",
    views: 12800,
    likes: 945,
    comments: 76,
    shares: 234,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    duration: "1:45",
    location: "Tokyo, Japan", // Moved to Japan
  },
  {
    id: 47,
    userId: 5,
    title: "Interview with Laid Off Tech Workers Discussing Job Search",
    description: "The layoffs hit hard. These engineers are navigating a changed landscape.",
    thumbnail: "/interview-with-laid-off-tech-workers-discussing-jo.jpg",
    author: "Marcus Thompson",
    views: 26700,
    likes: 2080,
    comments: 178,
    shares: 612,
    timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    duration: "3:23",
    location: "Bangalore, India", // Moved to India
  },
  {
    id: 48,
    userId: 5,
    title: "Startup Founder Explaining Company Pivot from Crypto",
    description: "From crypto to AI in 6 months. This is how startups survive.",
    thumbnail: "/startup-founder-explaining-company-pivot-from-cryp.jpg",
    author: "Marcus Thompson",
    views: 19400,
    likes: 1520,
    comments: 134,
    shares: 445,
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    duration: "2:34",
    location: "Tokyo, Japan", // Moved to Japan
  },
  {
    id: 49,
    userId: 5,
    title: "Co-working Space in Oakland with Remote Workers",
    description: "Oakland is becoming the new SF for tech workers. Cheaper rent, same opportunities.",
    thumbnail: "/co-working-space-in-oakland-with-remote-workers.jpg",
    author: "Marcus Thompson",
    views: 15600,
    likes: 1180,
    comments: 98,
    shares: 356,
    timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    duration: "2:12",
    location: "San Francisco, CA",
  },
  {
    id: 50,
    userId: 5,
    title: "Tech Company Cafeteria with Free Lunch Buffet",
    description: "The perks are still there at some companies. But for how long?",
    thumbnail: "/tech-company-cafeteria-with-free-lunch-buffet.jpg",
    author: "Marcus Thompson",
    views: 18200,
    likes: 1390,
    comments: 112,
    shares: 389,
    timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    location: "San Francisco, CA",
  },

  // Dr. Emily Watson (Boston Science Writer) - Now 5 in US, 2 in Canada, 2 in Australia, 1 in Singapore
  {
    id: 51,
    userId: 6,
    title: "Local Lab Makes Small Breakthrough in Cancer Research",
    description: "This won't cure cancer tomorrow, but it's a step forward. Science is about incremental progress.",
    thumbnail: "/scientists-in-laboratory-conducting-cancer-researc.jpg",
    author: "Dr. Emily Watson",
    views: 32400,
    likes: 2890,
    comments: 198,
    shares: 756,
    timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000),
    duration: "3:12",
    location: "Toronto, Canada", // Moved to Canada
  },
  {
    id: 52,
    userId: 6,
    title: "Children Interacting with Hands-On Biology Exhibit",
    description: "Science education starts young. This museum exhibit is getting kids excited about biology.",
    thumbnail: "/children-interacting-with-hands-on-biology-exhibit.jpg",
    author: "Dr. Emily Watson",
    views: 14800,
    likes: 1120,
    comments: 87,
    shares: 312,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    duration: "2:23",
    location: "Toronto, Canada", // Moved to Canada
  },
  {
    id: 53,
    userId: 6,
    title: "Scientist Researcher Being Interviewed in Laboratory",
    description: "Dr. Martinez explains her groundbreaking work on gene therapy. This is the future of medicine.",
    thumbnail: "/scientist-researcher-being-interviewed-in-laborato.jpg",
    author: "Dr. Emily Watson",
    views: 21600,
    likes: 1680,
    comments: 145,
    shares: 489,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    duration: "4:12",
    location: "Melbourne, Australia", // Moved to Australia
  },
  {
    id: 54,
    userId: 6,
    title: "Scientists Reviewing Research Papers and Documents",
    description: "Peer review is the backbone of science. Here's how it actually works.",
    thumbnail: "/scientists-reviewing-research-papers-and-documents.jpg",
    author: "Dr. Emily Watson",
    views: 16200,
    likes: 1240,
    comments: 98,
    shares: 367,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    duration: "2:45",
    location: "Boston, MA",
  },
  {
    id: 55,
    userId: 6,
    title: "Biotech Laboratory with Scientists Conducting Clinical Trials",
    description: "Inside a clinical trial. The process is rigorous for good reason.",
    thumbnail: "/biotech-laboratory-with-scientists-conducting-clin.jpg",
    author: "Dr. Emily Watson",
    views: 24800,
    likes: 1920,
    comments: 167,
    shares: 578,
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    duration: "3:34",
    location: "Singapore", // Moved to Singapore
  },
  {
    id: 56,
    userId: 6,
    title: "Explaining mRNA Technology to Non-Scientists",
    description: "Breaking down how mRNA vaccines work. It's simpler than you think.",
    thumbnail: "/scientist-explaining-mrna-technology-with-diagrams.jpg",
    author: "Dr. Emily Watson",
    views: 28900,
    likes: 2340,
    comments: 189,
    shares: 712,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    duration: "2:56",
    location: "Boston, MA",
  },
  {
    id: 57,
    userId: 6,
    title: "Lab Safety Protocols and Why They Matter",
    description: "Safety isn't just bureaucracy. These protocols save lives.",
    thumbnail: "/scientist-demonstrating-lab-safety-equipment.jpg",
    author: "Dr. Emily Watson",
    views: 12400,
    likes: 890,
    comments: 76,
    shares: 245,
    timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    duration: "2:12",
    location: "Boston, MA",
  },
  {
    id: 58,
    userId: 6,
    title: "The Reality of Scientific Funding",
    description: "Grant writing takes up 40% of a researcher's time. The system needs reform.",
    thumbnail: "/scientist-writing-grant-proposal-at-desk.jpg",
    author: "Dr. Emily Watson",
    views: 18600,
    likes: 1450,
    comments: 134,
    shares: 456,
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    duration: "3:23",
    location: "Boston, MA",
  },
  {
    id: 59,
    userId: 6,
    title: "Women in STEM: Progress and Challenges",
    description: "We've come far, but there's still work to do. Talking to female scientists about their experiences.",
    thumbnail: "/diverse-group-of-female-scientists-in-laboratory-s.jpg",
    author: "Dr. Emily Watson",
    views: 22100,
    likes: 1780,
    comments: 156,
    shares: 534,
    timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    duration: "3:45",
    location: "Sydney, Australia", // Moved to Australia
  },
  {
    id: 60,
    userId: 6,
    title: "Debunking Common Science Myths",
    description: "No, you don't only use 10% of your brain. Let's clear up some misconceptions.",
    thumbnail: "/scientist-explaining-brain-science-with-visual-aid.jpg",
    author: "Dr. Emily Watson",
    views: 26400,
    likes: 2120,
    comments: 178,
    shares: 623,
    timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    duration: "2:34",
    location: "Boston, MA",
  },

  // Robert Chen (NYC Business Analyst) - Now 5 in US (NYC), 2 in Germany, 1 UAE, 1 Brazil, 1 Hong Kong, 1 Mexico
  {
    id: 61,
    userId: 12,
    title: "Startup Founder Celebrating Funding Announcement in Office",
    description: "Series A closed at $15M. This startup's journey from garage to growth stage.",
    thumbnail: "/startup-founder-celebrating-funding-announcement-i.jpg",
    author: "Robert Chen",
    views: 19800,
    likes: 1560,
    comments: 128,
    shares: 445,
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    duration: "2:23",
    location: "Berlin, Germany", // Moved to Germany
  },
  {
    id: 62,
    userId: 12,
    title: "Person Using Bitcoin Cryptocurrency ATM Machine in City",
    description: "Crypto ATMs are popping up everywhere. But who's actually using them?",
    thumbnail: "/person-using-bitcoin-cryptocurrency-atm-machine-in.jpg",
    author: "Robert Chen",
    views: 24200,
    likes: 1890,
    comments: 167,
    shares: 567,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    duration: "1:45",
    location: "New York, NY",
  },
  {
    id: 63,
    userId: 12,
    title: "Financial Advisor Meeting with Young Professional About Investments",
    description: "Gen Z is investing differently than their parents. Here's what's changing.",
    thumbnail: "/financial-advisor-meeting-with-young-professional-.jpg",
    author: "Robert Chen",
    views: 16400,
    likes: 1290,
    comments: 98,
    shares: 378,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    duration: "3:12",
    location: "Dubai, UAE", // Moved to UAE
  },
  {
    id: 64,
    userId: 12,
    title: "Diverse Gig Economy Workers Including Uber Driver and Freelancer",
    description: "The gig economy is reshaping work. But is it sustainable?",
    thumbnail: "/diverse-gig-economy-workers-including-uber-driver-.jpg",
    author: "Robert Chen",
    views: 21800,
    likes: 1720,
    comments: 145,
    shares: 489,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    duration: "2:56",
    location: "New York, NY",
  },
  {
    id: 65,
    userId: 12,
    title: "Customers Shopping at Small Local Business Store on Main Street",
    description: "Small businesses are the backbone of the economy. Here's how they're adapting.",
    thumbnail: "/customers-shopping-at-small-local-business-store-o.jpg",
    author: "Robert Chen",
    views: 14600,
    likes: 1080,
    comments: 87,
    shares: 312,
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    duration: "2:34",
    location: "São Paulo, Brazil", // Moved to Brazil
  },
  {
    id: 66,
    userId: 12,
    title: "Wall Street Trading Floor During Market Hours",
    description: "The energy on the trading floor is electric. But algorithms are taking over.",
    thumbnail: "/busy-wall-street-trading-floor-with-traders-and-mo.jpg",
    author: "Robert Chen",
    views: 28400,
    likes: 3400,
    comments: 212,
    shares: 678,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    duration: "2:12",
    location: "New York, NY",
  },
  {
    id: 67,
    userId: 12,
    title: "Analyzing the Latest Fed Interest Rate Decision",
    description: "Breaking down what the Fed's decision means for your wallet.",
    thumbnail: "/federal-reserve-building-with-financial-charts-int.jpg",
    author: "Robert Chen",
    views: 22600,
    likes: 1820,
    comments: 156,
    shares: 534,
    timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    duration: "3:23",
    location: "Hong Kong", // Moved to Hong Kong
  },
  {
    id: 68,
    userId: 12,
    title: "Real Estate Market Trends in Major Cities",
    description: "Housing prices are cooling, but not everywhere. Here's what the data shows.",
    thumbnail: "/city-skyline-with-real-estate-for-sale-signs-housi.jpg",
    author: "Robert Chen",
    views: 19200,
    likes: 1520,
    comments: 134,
    shares: 456,
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    duration: "2:45",
    location: "New York, NY",
  },
  {
    id: 69,
    userId: 12,
    title: "The Rise of Buy Now, Pay Later Services",
    description: "BNPL is everywhere. But is it creating a debt crisis?",
    thumbnail: "/person-using-smartphone-for-buy-now-pay-later-paym.jpg",
    author: "Robert Chen",
    views: 17800,
    likes: 1390,
    comments: 112,
    shares: 389,
    timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    duration: "2:56",
    location: "Mexico City, Mexico", // Moved to Mexico
  },
  {
    id: 70,
    userId: 12,
    title: "Economic Indicators Every Investor Should Watch",
    description: "GDP, unemployment, inflation - here's how to read the economic tea leaves.",
    thumbnail: "/financial-analyst-reviewing-economic-indicators-ch.jpg",
    author: "Robert Chen",
    views: 15400,
    likes: 1180,
    comments: 98,
    shares: 334,
    timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    duration: "3:12",
    location: "Berlin, Germany", // Moved to Germany
  },

  // David Park (Zoo) - Now 4 in US (San Diego), 2 in South Africa, 2 in Australia, 1 Thailand, 1 Kenya, 1 Argentina
  {
    id: 71,
    userId: 8,
    title: "Rare Bird Species Spotted in Local Park",
    description: "This migratory bird hasn't been seen here in 20 years. Climate change is shifting patterns.",
    thumbnail: "/rare-colorful-migratory-bird-perched-on-branch-in-.jpg",
    author: "David Park",
    views: 26800,
    likes: 2180,
    comments: 178,
    shares: 912,
    timestamp: new Date(Date.now() - 9 * 60 * 60 * 1000),
    duration: "2:12",
    location: "Cape Town, South Africa", // Moved to South Africa
  },
  {
    id: 72,
    userId: 8,
    title: "Morning Feeding Routine with the Lions",
    description: "The lions know the schedule better than I do. Watch how they react when they hear the truck.",
    thumbnail: "/zookeeper-feeding-lions-at-zoo-morning-routine.jpg",
    author: "David Park",
    views: 31200,
    likes: 2560,
    comments: 198,
    shares: 712,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    duration: "2:34",
    location: "San Diego, CA",
  },
  {
    id: 73,
    userId: 8,
    title: "New Exhibit: Discovering the Nocturnal World",
    description: "Our new nocturnal exhibit lets you see animals that are usually hidden. It's incredible.",
    thumbnail: "/nocturnal-animals-exhibit-at-zoo-with-dim-lighting.jpg",
    author: "David Park",
    views: 22400,
    likes: 1820,
    comments: 145,
    shares: 534,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    duration: "3:12",
    location: "Sydney, Australia", // Moved to Australia
  },
  {
    id: 74,
    userId: 8,
    title: "Caring for Our Elderly Elephant",
    description: "Mara is 52 years old and needs special care. Here's what goes into caring for a senior elephant.",
    thumbnail: "/elderly-elephant-being-cared-for-by-zookeeper.jpg",
    author: "David Park",
    views: 28600,
    likes: 2340,
    comments: 189,
    shares: 678,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    duration: "3:45",
    location: "San Diego, CA",
  },
  {
    id: 75,
    userId: 8,
    title: "Training a New Zookeeper",
    description: "Teaching the next generation of zookeepers. It's more than just feeding animals.",
    thumbnail: "/experienced-zookeeper-training-new-employee-at-zoo.jpg",
    author: "David Park",
    views: 16800,
    likes: 1320,
    comments: 112,
    shares: 389,
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    duration: "2:56",
    location: "Bangkok, Thailand", // Moved to Thailand
  },
  {
    id: 76,
    userId: 8,
    title: "Conservation Efforts for Local Wildlife",
    description: "We're not just a zoo - we're actively working to protect endangered species in the wild.",
    thumbnail: "/wildlife-conservation-team-working-to-protect-enda.jpg",
    author: "David Park",
    views: 24200,
    likes: 1920,
    comments: 167,
    shares: 612,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    duration: "3:23",
    location: "San Diego, CA",
  },
  {
    id: 77,
    userId: 8,
    title: "Behind the Scenes: Zoo Vet Check-up",
    description: "Annual health check for our giraffe. The vet team is incredible.",
    thumbnail: "/veterinarian-examining-giraffe-at-zoo-health-check.jpg",
    author: "David Park",
    views: 19400,
    likes: 1560,
    comments: 134,
    shares: 467,
    timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    duration: "2:45",
    location: "Nairobi, Kenya", // Moved to Kenya
  },
  {
    id: 78,
    userId: 8,
    title: "New Arrival: A Healthy Baby Tapir!",
    description: "We welcomed a baby tapir this week! Mom and baby are doing great.",
    thumbnail: "/baby-tapir-with-mother-at-zoo-newborn-animal.jpg",
    author: "David Park",
    views: 34600,
    likes: 2890,
    comments: 223,
    shares: 823,
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    duration: "2:12",
    location: "San Diego, CA",
  },
  {
    id: 79,
    userId: 8,
    title: "Observing Penguin Behavior",
    description: "Penguins are more complex than people think. Watch how they interact and communicate.",
    thumbnail: "/group-of-penguins-at-zoo-exhibit-social-behavior.jpg",
    author: "David Park",
    views: 21800,
    likes: 1720,
    comments: 156,
    shares: 534,
    timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    duration: "2:34",
    location: "Buenos Aires, Argentina", // Moved to Argentina
  },
  {
    id: 80,
    userId: 8,
    title: "Education Day at the Zoo",
    description: "School groups visit every week. Seeing kids get excited about animals never gets old.",
    thumbnail: "/children-on-school-field-trip-learning-at-zoo-with.jpg",
    author: "David Park",
    views: 17200,
    likes: 1390,
    comments: 112,
    shares: 445,
    timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    duration: "2:23",
    location: "Cape Town, South Africa", // Moved to South Africa
  },
]
